sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
  - master
  - /^greenkeeper/.*$/

node_js:
  - '8'
  - '7'
  - '6'
before_script:
  - npm prune
script:
  - npm test
after_success:
  - npm run semantic-release
